/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/chat/threads': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['listThreads'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/chat/stream': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['chatStream'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/dashboard': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getDashboard'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/dashboard/summary': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getDashboardSummary'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getMe'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/me/profile': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getProfile'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations['updateProfile'];
    trace?: never;
  };
  '/agents/{agent_id}/detail': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get enriched detail for one agent */
    get: operations['getAgentDetail'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Thread: {
      id: string;
      title: string;
      /** Format: date-time */
      updated_at: string;
    };
    AgentSummary: {
      /** @enum {string} */
      agent:
        | 'sleep'
        | 'workout'
        | 'nutrition'
        | 'mood'
        | 'habits'
        | 'recovery'
        | 'medication'
        | 'finance'
        | 'calendar'
        | 'home';
      label: string;
      metric: string;
      /** @enum {string} */
      tint: 'success' | 'warn' | 'danger' | 'neutral';
      detail?: string | null;
      /** Format: float */
      progress?: number | null;
    };
    Dashboard: {
      agents: components['schemas']['AgentSummary'][];
    };
    Me: {
      id: string;
      /** @enum {string} */
      voice_preset: 'calm_coach' | 'data_literate' | 'clinical' | 'hype';
    };
    BodyProfile: {
      height_cm?: number | null;
      weight_kg?: number | null;
      age?: number | null;
      /** @enum {string|null} */
      sex?: 'male' | 'female' | null;
      /** @enum {string|null} */
      activity_level?: 'sedentary' | 'light' | 'moderate' | 'active' | 'very_active' | null;
      calorie_goal_override?: number | null;
      tdee_kcal?: number | null;
    };
    BodyProfileUpdate: {
      height_cm?: number | null;
      weight_kg?: number | null;
      age?: number | null;
      /** @enum {string|null} */
      sex?: 'male' | 'female' | null;
      /** @enum {string|null} */
      activity_level?: 'sedentary' | 'light' | 'moderate' | 'active' | 'very_active' | null;
      calorie_goal_override?: number | null;
    };
    AgentDetail: {
      /** @enum {string} */
      agent:
        | 'sleep'
        | 'workout'
        | 'nutrition'
        | 'mood'
        | 'habits'
        | 'recovery'
        | 'medication'
        | 'finance'
        | 'calendar';
      /** @description Formula-computed 1-2 sentence summary. Empty string when insufficient data. */
      insight: string;
      /** @description Flat dict of agent-specific metric values. Keys differ per agent. */
      metrics: {
        [key: string]: unknown;
      };
      history: {
        /** Format: date */
        date: string;
        /** Format: float */
        value: number;
        label: string;
      }[];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  listThreads: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description ok */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Thread'][];
        };
      };
    };
  };
  chatStream: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          message: string;
          thread_id: string;
        };
      };
    };
    responses: {
      /** @description SSE stream of events */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getDashboard: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description ok */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Dashboard'];
        };
      };
    };
  };
  getDashboardSummary: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description ok */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Dashboard'];
        };
      };
    };
  };
  getMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description ok */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Me'];
        };
      };
    };
  };
  getProfile: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description ok */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BodyProfile'];
        };
      };
    };
  };
  updateProfile: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['BodyProfileUpdate'];
      };
    };
    responses: {
      /** @description ok */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            ok?: boolean;
          };
        };
      };
    };
  };
  getAgentDetail: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        agent_id:
          | 'sleep'
          | 'workout'
          | 'nutrition'
          | 'mood'
          | 'habits'
          | 'recovery'
          | 'medication'
          | 'finance'
          | 'calendar';
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Agent detail with history and insight */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AgentDetail'];
        };
      };
      /** @description Unknown agent_id */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
